docs_dir: docs_src
site_dir: docs
site_name: Perekrestok API
site_url: https://example.com
nav:
  - Home: index.md
plugins:
  - search
  - gen-files:
      scripts:
        - docs_src/scripts/gen_ref.py
  - literate-nav:
      nav_file: SUMMARY.md
