name: tests

on:
  pull_request:
  schedule:
    - cron: "17 3 * * *"  # daily at 03:17 UTC
  workflow_dispatch:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.12"

permissions:
  contents: read

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version || '3.12' }}
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            pyproject.toml

      - name: Install system deps (optional)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y graphviz

      - name: Install project (dev)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          fi
          pip install -e ".[dev]" || pip install -e .

      - name: Run tests
        run: |
          if make -n test >/dev/null 2>&1; then
            make test
          elif [ -f pyproject.toml ] || [ -f setup.cfg ] || [ -f setup.py ]; then
            python -m pytest -q
          else
            echo "No known test command found"; exit 1
          fi
